# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Usar Ubuntu 20.04 LTS
  config.vm.box = "ubuntu/focal64"
  
  # Configurar la red para que la máquina virtual use la conexión a Internet de la máquina host
  config.vm.network "public_network"
  
  # Configurar la memoria y CPUs (opcional)
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  # Provisión: ejecutar el script de instalación en la máquina virtual
  config.vm.provision :shell, path: "bootstrap.sh"

  # Configurar el reenvío de puertos (acceder al puerto 80 de Apache)
  config.vm.network "forwarded_port", guest: 80, host: 8081
end
